#!/bin/bash
# Generated by FINN for debugging/re-running
# This script can be edited and re-run manually
# Generated: 2026-06-04 20:53:18

cd /home/kirthanar/brainsmith_projects/lenet/build/vivado_stitch_proj_ne6oa2sk

vivado -mode batch -source make_project.tcl
